services:
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASS}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_ROOT_USER} -d ${PG_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api:
    build: ./api
    restart: always
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action: sync
          path: ./api
          target: /usr/src/app
          ignore:
            - node_modules/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data:
