services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASS}
      POSTGRES_DB: ${PG_DATABASE}
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data:
